### ISSUE TITLE
Css tidak sejajar

### ISSUE THREAD

**Issue by Alpha666** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-aldebaran#1]
Pada halaman index.php css untuk "Read More ->" sebelah kiri tidak sejajar sementara tengah dan kanan sudah sejajar. Sudah di coba di 4 browser sekaligus dan hasilnya sama.

![bug 1 brave](https://user-images.githubusercontent.com/53895082/66940081-7e724e80-f06e-11e9-93b5-656e6dee9685.png)
![bug 1 chrome](https://user-images.githubusercontent.com/53895082/66940083-7f0ae500-f06e-11e9-9781-c3f158838dac.png)
![bug 1 edge](https://user-images.githubusercontent.com/53895082/66940085-7fa37b80-f06e-11e9-8173-19dbf4350d9b.png)
![bug 1 firefox](https://user-images.githubusercontent.com/53895082/66940086-7fa37b80-f06e-11e9-8206-f218d10c9336.png)

**Comment by Rezaaisyi** [comment]
Siap gan

Pada tanggal Rab, 16 Okt 2019 23:41 Christian Andrew <
notifications@github.com menulis:

**Comment by hanbaebae** [comment]
terima kasih sudah kita perbaiki.
