### ISSUE TITLE
Teks Tersembunyi

### ISSUE THREAD

**Issue by Senivri** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-aldebaran#10]
Banyak teks tersembunyi pada halaman donasi_saya.php

![Screenshot 2019-10-17 15 46 13](https://user-images.githubusercontent.com/55181810/66993152-4eba5980-f0f5-11e9-89b0-ea5c36c90394.png)
![Screenshot 2019-10-17 15 46 18](https://user-images.githubusercontent.com/55181810/66993153-4eba5980-f0f5-11e9-9c95-5f52a2725dc6.png)
![Screenshot 2019-10-17 15 46 26](https://user-images.githubusercontent.com/55181810/66993154-4f52f000-f0f5-11e9-87cc-38eca5825b9a.png)
![Screenshot 2019-10-17 15 46 30](https://user-images.githubusercontent.com/55181810/66993155-4f52f000-f0f5-11e9-8628-719f4e81d425.png)

**Comment by indrawidnyana** [comment]
maaf itu bukan teks tersembunya mas, tapi memang design kami seperti itu.. , akan kami perbaiki dengan mengganti warna fontnya

terimakasih atas sarannya
