### ISSUE TITLE
Link tidak berfungsi

### ISSUE THREAD

**Issue by Senivri** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-aldebaran#11]
Link pada Logo 'tu.skul' pada halaman galangdana.html, inbox.html, dan akun.html menuju ke 'Object not Found'

![Screenshot 2019-10-17 16 06 26](https://user-images.githubusercontent.com/55181810/66994811-19633b00-f0f8-11e9-87af-ac206242c2fb.png)
![Screenshot 2019-10-17 16 06 18](https://user-images.githubusercontent.com/55181810/66994813-19fbd180-f0f8-11e9-8163-5599fafd36c8.png)

**Comment by Rezaaisyi** [comment]
harusnya menuju ke index,php, sudah kita perbaiki. Terima kasih bro.
