### ISSUE TITLE
dari inbox.html ingin kembali ke home yang muncul malah login.php?pesan=gagal

### ISSUE THREAD

**Issue by fvldi** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-aldebaran#12]
mungkin salah di href:"" nya gann semangaaat
![image](https://user-images.githubusercontent.com/55771340/67095601-84883c80-f1e0-11e9-950d-cec4eefc59f0.png)

**Comment by Rezaaisyi** [comment]
sudah kita perbaiki gan terima kasih
