### ISSUE TITLE
Maaf ini apa ya

### ISSUE THREAD

**Issue by nashirat** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-aldebaran#16]
![image](https://user-images.githubusercontent.com/55182333/67175895-0307f880-f3f2-11e9-998f-7216428efe10.png)

**Comment by indrawidnyana** [comment]
itu errornya dimana mas/mbak ? saat melakukan apa ?

**Comment by nashirat** [comment]
saat klik donasi sekarang mas

**Comment by Rezaaisyi** [comment]
seharusnya gambar tetapi belum terupload. Terima kasih
