### ISSUE TITLE
page not found

### ISSUE THREAD

**Issue by nashirat** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-aldebaran#17]
![image](https://user-images.githubusercontent.com/55182333/67175955-3cd8ff00-f3f2-11e9-8f67-00de5d29465e.png)

**Comment by indrawidnyana** [comment]
![1 1](https://user-images.githubusercontent.com/54881761/67696608-c469d380-f9d9-11e9-8a31-9eed112dda7a.png)

terimakasih mas atas masukannya, sekarang untuk profile.html yang sebelumnya sudah kami ganti menjadi profile.php dan pada laman tersebut sudah dapat digunakan sebagaimana mestinya
