### ISSUE TITLE
inbox issue

### ISSUE THREAD

**Issue by peacefulhack** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-aldebaran#18]
inbox harusnya tidak boleh di akses oleh orang yang belum login
![image](https://user-images.githubusercontent.com/49645946/67189047-b8997280-f417-11e9-91f2-f2f0d8068fec.png)

**Comment by indrawidnyana** [comment]
![1 1](https://user-images.githubusercontent.com/54881761/67695928-7e604000-f9d8-11e9-96dc-e523c6630a5f.png)
terimakasih mas atas masukannya, sudah kami perbaiki untuk inboxnya sehingga apabila belum login maka jika user masuk ke inbox akan diminta untuk register dan login terlebih dahulu
