### ISSUE TITLE
Link tidak berfungsi 

### ISSUE THREAD

**Issue by Alpha666** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-aldebaran#2]
Masih sama dengan bug sebelumnya pada halaman index.php link "Read More ->" tidak berfungsi dan hanya mengembalikan ke bagian atas page index.php

![bug 1 firefox](https://user-images.githubusercontent.com/53895082/66940185-bbd6dc00-f06e-11e9-95f2-64c665ca4bd7.png)

**Comment by Rezaaisyi** [comment]
readmore sudah kita perbaiki gan. terima kasih
