### ISSUE TITLE
harusnya tidak perlu di commit

### ISSUE THREAD

**Issue by peacefulhack** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-aldebaran#20]
untuk source code yang anda copy tidak perlu di taruh di github.
![image](https://user-images.githubusercontent.com/49645946/67189275-20e85400-f418-11e9-9f57-e9c85d1842d4.png)

**Comment by Rezaaisyi** [comment]
oke sudah kita hapus mas. terima kasih.
