### ISSUE TITLE
Belum Login, tapi ada Page DonasiKu

### ISSUE THREAD

**Issue by bagasimmanuel** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-aldebaran#21]
![Screenshot from 2019-10-21 22-47-48](https://user-images.githubusercontent.com/55182200/67190425-221a8080-f41a-11e9-904f-7ec2dfc09ad5.png)
Mungkin akan lebih baik jika fitur Donasiku ditampilkan hanya jika user sudah login

**Comment by indrawidnyana** [comment]
maaf , memang rencananya seperti itu yang dimana kedepannya apabila ingin melakukan donasi user tetap harus register dann login terlebih dahulu

terimakasih
