### ISSUE TITLE
home pagenya ga ad yg ke ref/link :((

### ISSUE THREAD

**Issue by Krauszie** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-aldebaran#22]
![Capture](https://user-images.githubusercontent.com/50489529/67748837-6206e680-fa5e-11e9-977d-7a4ce869bc19.jpg)
![Capture1](https://user-images.githubusercontent.com/50489529/67748838-6206e680-fa5e-11e9-8a53-f5cc5bc13bf6.JPG)

**Comment by Rezaaisyi** [comment]
memang masih seperti itu mas, kedepan akan kita tambahkan
