### ISSUE TITLE
Password dalam bentuk plaintext

### ISSUE THREAD

**Issue by Alpha666** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-aldebaran#3]
Pada bagian database seharusnya password dalam bentuk hash dan bukan dalam bentuk plaintext karena sangat rawan. Jika menggunakan password dalam bentuk plaintext maka kemungkinan besar akan terjadi sniffing pada web anda.

![bug 2](https://user-images.githubusercontent.com/53895082/66940487-37388d80-f06f-11e9-957e-324b7c4659fa.png)

**Comment by indrawidnyana** [comment]
![password](https://user-images.githubusercontent.com/54881761/67697169-b5cfec00-f9da-11e9-8f9d-fcb7a88dcc26.jpg)

terimakasih mas atas masukannya, saat ini sudah kami perbaiki dan untuk password tidak berupa plaintext lagi seperti sebelumnya
