### ISSUE TITLE
Salah link gan

### ISSUE THREAD

**Issue by Alpha666** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-aldebaran#4]
Pada halaman index.php ditekan tombol navigasi "HOME" maka akan berpindah ke login.php dan menampilkan error "username dan password tidak sesuai" padahal belum ada username dan password yang di inputkan. 

![bug 3](https://user-images.githubusercontent.com/53895082/66940878-f1c89000-f06f-11e9-868a-9a49b9b3ca7b.png)

**Comment by Rezaaisyi** [comment]
baik terima kasih, sudah kita perbaiki
