### ISSUE TITLE
Halaman profil tidak ada 

### ISSUE THREAD

**Issue by Alpha666** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-aldebaran#5]
Setelah melakukan login dan memilih profile namun yang terjadi adalah halaman profile tidak ada.

![bug 4](https://user-images.githubusercontent.com/53895082/66941157-88954c80-f070-11e9-951d-ce2cc8a18aea.png)
![bug 4 hasil](https://user-images.githubusercontent.com/53895082/66941200-99de5900-f070-11e9-9d52-4e570ebf2a2f.png)

**Comment by Rezaaisyi** [comment]
sudah kita tambahkan halaman profil, bro. Terima Kasih.
