### ISSUE TITLE
Menu galang dana tidak bisa di click

### ISSUE THREAD

**Issue by Alpha666** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-aldebaran#6]
Menu galang dana untuk mahasiswa tidak dapat di click 

![bug 5](https://user-images.githubusercontent.com/53895082/66941362-f2155b00-f070-11e9-9a66-602cd3317bd7.png)

**Comment by Rezaaisyi** [comment]
sudah kita tambahkan, terima kasih
