### ISSUE TITLE
Email yang bisa di isi asal

### ISSUE THREAD

**Issue by Alpha666** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-aldebaran#7]
pada halaman login.php bagian email masih bisa di isi dengan huruf acak (dimana seharusnya untuk subscribe harus menggunakan email)

![bug 6](https://user-images.githubusercontent.com/53895082/66941561-59cba600-f071-11e9-88fd-80db18c21408.png)

**Comment by Rezaaisyi** [comment]
oke terima kasih sudah kita tambah menggunakan hash dari php
