### ISSUE TITLE
link akun salah

### ISSUE THREAD

**Issue by MilenFifi** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-aldebaran#8]
waktu aku belum sign up atau login lalu klik link akun aku langsung masuk sebagai pengguna tapi link profil tidak bisa/object not found!
![Screenshot (7)](https://user-images.githubusercontent.com/55182134/66989543-bde07f80-f0ee-11e9-8908-78899a444ebb.png)

**Comment by Rezaaisyi** [comment]
baik terima kasih href sudah kami perbaiki
