### ISSUE TITLE
info buat kamu tidak bisa ditekan, selalu pada page yang sama

### ISSUE THREAD

**Issue by belladewusa** [2019Ganjil-PemrogramanBerbasisWeb/tugas2-web-aldebaran#9]
![Screenshot (106)](https://user-images.githubusercontent.com/55181780/66990622-c3d76000-f0f0-11e9-85d6-64d03eddd12f.png)

**Comment by Rezaaisyi** [comment]
untuk info memang kita belum menentukan jadi memang belum berfungsi
